import os
from dotenv import load_dotenv


load_dotenv()


GCP_PROJECT_ID = os.getenv("GCP_PROJECT_ID")
GCS_BUCKET_NAME = os.getenv("GCS_BUCKET_NAME")
BIGQUERY_DATASET = os.getenv("BIGQUERY_DATASET")
CMS_HOSPITAL_API_URL = os.getenv("CMS_HOSPITAL_API_URL")
CMS_HOSPITAL_READMISSIONS_API_URL = os.getenv("CMS_HOSPITAL_READMISSIONS_API_URL")
CMS_HOSPITAL_HCAHPS_API_URL = os.getenv("CMS_HOSPITAL_HCAHPS_API_URL")
CMS_HOSPITAL_MORTALITY_API_URL = os.getenv("CMS_HOSPITAL_MORTALITY_API_URL")
CMS_HOSPITAL_TIMELY_EFFECTIVE_CARE_API_URL = os.getenv("CMS_HOSPITAL_TIMELY_EFFECTIVE_CARE_API_URL")
CMS_HOSPITAL_HAI_API_URL = os.getenv("CMS_HOSPITAL_HAI_API_URL")
CMS_HOSPITAL_OUTPATIENT_IMAGING_API_URL = os.getenv("CMS_HOSPITAL_OUTPATIENT_IMAGING_API_URL")

